import type { Metadata } from 'next';
import { Inter } from 'next/font/google';
import './globals.css';
import { ReactNode } from 'react';

const inter = Inter({
  variable: '--font-inter',
  subsets: ['latin'],
});

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

export default function RootLayout({
  children,
}: Readonly<{
  children: ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${inter.variable} antialiased`}
      >
        <header className="bg-white shadow py-6 px-4 sticky top-0 z-10">
          <h1 className="text-3xl text-center font-bold text-gray-900">TON NFT Marketplace</h1>
        </header>

        {children}
      </body>
    </html>
  );
}
